"""Shared validation limits for API input (PII / abuse resistance)."""

NOTE_TEXT_MAX_LENGTH = 1000
SPOT_NAME_MAX_LENGTH = 120
SPOT_LIST_MAX_RADIUS_M = 50_000
ENGAGEMENT_METADATA_MAX_JSON_BYTES = 2048
ENGAGEMENT_METADATA_MAX_KEYS = 24
